
services:
  backend-express:
    container_name: backend-express
    build:
      context: .
      dockerfile: backend-express/Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./backend-express:/app/backend-express

      # prevent node_modules overwrite
      - /app/backend-express/node_modules

      # share root pnpm store cache (speed boost)
      - pnpm-store:/root/.local/share/pnpm/store

    env_file:
      - .env

    command: pnpm --filter backend-express dev    
volumes:
  pnpm-store: