
services:
  redis: 
    image: redis:7
    container_name: backend-express-pg-redis
    ports:
      - "6379:6379"
  db: # run postgres container on port 5432
    image: postgres:16
    container_name: backend-express-pg-postgres
    restart: unless-stopped
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotes-keeper
    ports: 
      - "5432:5432"
    volumes: # map volume to /var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
volumes: # create volume
  postgres_data:
